### PR TITLE
Split EntitiesDescriptor class up based on its two purposes

### PR DESCRIPTION
**Pull request by smangelsdorf**
Addresses a couple of issues with the existing db structure:

* `EntitiesDescriptor` was a dual-concern class, which modelled parts of the input to `saml-service` from other sources and parts of the output created during metadata generation.
* The upcoming addition of `RawEntityDescriptor`, which stores a blob of XML in the database for direct rendering into the output metadata, needed some changes to the hierarchy to prevent duplicated loops everywhere for the extra data type.

The new model classes are:

* `MetadataInstance` &mdash; Models an output of `saml-service`. Currently there's no way in the schema to select which `EntityDescriptor` records will be included in a metadata instance. This can be implemented after #25 is merged.
* `EntitySource` &mdash; Models an input to `saml-service`. The input may be an external metadata source, or it may be synced from another service (i.e. FR) or held entirely locally.

    `EntitySource#rank` describes the precedence of the `EntityDescriptor` records from this source. If a `MetadataInstance` is being rendered but selects the same `entityID` from two or more `EntitySource` parents, the one with the highest rank will be used during metadata generation. (Not implemented yet)
* `KnownEntity` &mdash; Simply "an entity known to `saml-service`". The entity may be described by a full `EntityDescriptor` hierarchy, or it may have some other structure to be defined in a future change. (Immediately, `RawEntityDescriptor`).

This change **removes** the ability to have nested `EntitiesDescriptor` nodes in the output, because there is now no way to model it in the database. We could easily add this back in the future if the database schema supported it somehow, but for now it would just be dead code.

### CODE REVIEW

**Comment by smangelsdorf** [comment]
One potential issue here is that `EntitySource` no longer records the extensions from an `EntitiesDescriptor` imported into `saml-service`. We may need to look at where / how this needs to be recorded so that we can still generate the output we wanted to generate. Pending discussion.

**Comment by smangelsdorf** [comment]
I won't add any more to this - will save extra functionality for when it's actually needed by another feature.

MetadataInstance tagging is probably best left for another day.

Awaiting review feedback.

**Comment by bradleybeddoes** [comment]
re: EntitiesDescriptor extensions, I believe we've modelled all the major ones (rpi/ui etc) in DB but something could still come up. Could MetadataInstance hold this a value (text field) like the previous impl of EntitiesDescriptor allowed for?

I am good apart from this discussion btw.

**Comment by smangelsdorf** [comment]
If that happens I would prefer to add a new model + table to support this hypothetical future extension. We're at a point where we don't have to be scared of code changes / redeployment, so let's use that to our advantage.

Happy to be swayed.

**Comment by bradleybeddoes** [comment]
This was more a "how we could solve it like other models do" hypothetical so I am also happy to move on.

**Comment by bradleybeddoes** [comment]
Looks like a successful split of EntitiesDescriptor to me

**Pull request merged**
