### PR TITLE
rspec Sha1 issue

### PR DESCRIPTION
**Pull request by bo-aaf**
Error with ruby v3 upgrade. Currently this is set to ruby v2.

Running will pass the test
```
make run-image-tests FILE=./spec/metadata/saml_spec.rb:486
```

However when the ruby version is switched to version 3
```
rbenv local 3.2.2
make build-image
make run-image-tests FILE=./spec/metadata/saml_spec.rb:486
```

This fails the test

```
Metadata::Saml
  ds:Signature Root EntityDescriptor
    has a <Signature> element, c14n method, reference element, signed, and transforms
    with a signed document
      using sha256
        uses the correct signature method
        includes the digest value
        includes the signature value
        specifies the digest algorithm
        is schema-valid
      using sha1
        is schema-valid (FAILED - 1)
        includes the digest value (FAILED - 2)
        uses the correct signature method (FAILED - 3)
        specifies the digest algorithm (FAILED - 4)
        includes the signature value (FAILED - 5)

Failures:

  1) Metadata::Saml ds:Signature Root EntityDescriptor with a signed document using sha1 is schema-valid
     Failure/Error: Xmldsig::SignedDocument.new(builder.doc.to_xml(indent: 2)).sign(key)
     
     OpenSSL::PKey::PKeyError:
       EVP_DigestSignInit: invalid digest
     Shared Example Group: "ds:Signature xml" called from ./spec/metadata/saml_spec.rb:486
     # ./lib/metadata/saml.rb:49:in `sign'
     # ./spec/support/metadata/signature.rb:77:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:27:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:26:in `block (2 levels) in <top (required)>'
```

The error seems to be caused by  `Xmldsig::SignedDocument` tried upgrading that gem didn't work. 
Might have something to do with changes in ruby v3 SSL library can't be sure for now. Having said that this works in my local M1 machine with no issues. There is some incompatibitilty issue with centOS in docker...

### CODE REVIEW

**Comment by phyzical** [comment]
@bo-aaf this current pr is still running ruby 2.X and fails though ?

**Comment by phyzical** [comment]
passed for me on 3.0.5
image
trying 3.2.2 now

**Comment by phyzical** [comment]
image
this is the only difference intems of the base image besides whatever is installed during ruby-build

**Comment by bo-aaf** [comment]
@phyzical Did have a conversation with Waldo on this. Apparantly we are still using sha1 in production. adding this variable here https://github.com/ausaccessfed/saml-service/pull/369/commits/0214cb108386a53d071ce1d491376cdf2341487e
fix the issue.

**Comment by bo-aaf** [comment]
refer to https://github.com/ausaccessfed/saml-service/pull/369

**Pull request closed without merging**
