### PR TITLE
Deprecate sha1 metadata instances

### PR DESCRIPTION
**Pull request by bo-aaf**
sha1 signing is deprecated and can be accessed using `/mdq/aaf-legacy/entities`. When I checked the logs, there has not been any access to this endpoint for the past 3 months. Having sha1 endpoints respond to with `not_found` is much safer approach rather than removing sha1 records in `metadata_instances` model.

Credits to Waldo giving this suggestion

Resolves [#371](https://github.com/ausaccessfed/saml-service/issues/371)

### CODE REVIEW

**Review by matthew-puku — COMMENTED** [review]
Have we told `metadata-distribution` to stop requesting this metadata instance? i imagine it will alert

**Comment by bo-aaf** [comment]
> Have we told `metadata-distribution` to stop requesting this metadata instance? i imagine it will alert

Good question! Based on the logs from saml-service. I haven't seen it making any calls to that endpoint over the past 3 months (with the exception of 31st of may where we tested the endpoint). 

If i look at env for `SOURCES_STRING` under `metadata-distribution` I did noticed its configured with `https://saml.aaf.edu.au/mdq/aaf-legacy/entities~~aaf-legacy-metadata.xml~~false~~2019-07-15,`
which gave me the impression that is configured to not call it. Even if its called it should appear in the saml service logs. But these my reasons why i dont think its calling it

**Review by matthew-puku — APPROVED** [review]

**Review by waldofouche — APPROVED** [review]

**Comment by phyzical** [comment]
@bo-aaf that false is for this 

```
  diff: sources[2] == 'true'
 ```

it will still be getting called.

the correct solution is  to
* remove the test for sha1 
* and the logic for sha1
* remove that env allowing sha1 on the container
* and update the db entries to be sha256 not sha1

**Comment by vladimir-mencl-eresearch** [comment]
Agree with @phyzical 's comment above.  Right now, request routing for SHA1 metadata instances is blocked, but the code supporting SHA1 is still there and tests for SHA1 are still being run.  (And they pass only because they bypass the request routing and invoke the signing directly)

**Pull request merged**
