### PR TITLE
App: add health check URL

### PR DESCRIPTION
**Pull request by vladimir-mencl-eresearch**
To assist with monitoring.

Check redis and DB connection and return 200 OK if both succeed, otherwise fail.

### CODE REVIEW

**Comment by vladimir-mencl-eresearch** [comment]
Rebased on `develop`

**Comment by vladimir-mencl-eresearch** [comment]
Rebased on `develop` - Ruby 2.7.0 / #214

**Comment by vladimir-mencl-eresearch** [comment]
Rebased on `develop` - Ruby 2.7.0 / #216

**Comment by vladimir-mencl-eresearch** [comment]
Rebased on `develop` / #219 .  @bradleybeddoes , would you be able to review this?

**Comment by bradleybeddoes** [comment]
@vladimir-mencl-eresearch we're not going to bring this in to our tree currently, trying to maintain status quo as much as possible whilst we work through core tooling considerations internally.

**Comment by vladimir-mencl-eresearch** [comment]
Hi @bradleybeddoes , thanks for the reply.

Reason for the functionality here was the SAML Service has no URL we could point monitoring at - nothing that would take an ordinary HTTP request and respond with a reasonably sized response (`/api/discovery/entities` was the only URL accepting a simple request without specialized headers, but the response would still be large and costly).

But I can just merge that internally in our fork, accepting that decision.

Cheers,
Vlad

**Pull request closed without merging**
